// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// AboutTopic is the predicate function for abouttopic builders.
type AboutTopic func(*sql.Selector)

// Image is the predicate function for image builders.
type Image func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Work is the predicate function for work builders.
type Work func(*sql.Selector)
