version: 2

updates:
  - package-ecosystem: gomod
    directory: "/backend"
    schedule:
      interval: daily
      time: "11:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 20

  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: daily
      time: "11:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 20
